

version: "3"

services:

  server_part5:
    build:
      context: part5/
      dockerfile: Dockerfile


  server_nginx:
    image: nginx:latest
    volumes:
      - ./part6/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - server_part5
